name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'config.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Read config
        id: read-config
        uses: jaspernbrouwer/powershell-yaml@1.3
        with:
          path: 'config.yaml'

      - name: Set environment variables
        run: |
          echo "BASE_IMAGE_VERSION=${{ steps.read-config.outputs.base_image_version }}" >> $GITHUB_ENV
          echo "NVM_VERSION=${{ steps.read-config.outputs.nvm_version }}" >> $GITHUB_ENV
          echo "NODE_VERSION=${{ steps.read-config.outputs.node_version }}" >> $GITHUB_ENV
          echo "MONGODB_VERSION=${{ steps.read-config.outputs.mongodb_version }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ steps.read-config.outputs.tag_version }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . --build-arg BUILD_FROM=$BASE_IMAGE_VERSION --build-arg NVM_VERSION=$NVM_VERSION --build-arg NODE_VERSION=$NODE_VERSION --build-arg MONGODB_VERSION=$MONGODB_VERSION -t my-image-name:$IMAGE_TAG

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/addon-base-ubuntu-node-mongo:${IMAGE_TAG}

      - name: Clean up post build/test
        run: docker rmi my-image-name:$IMAGE_TAG

      - name: Complete
        run: echo "Build and push completed on $(date)"
