name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'config.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install yq
        run: sudo snap install yq

      - name: Read config
        id: config
        run: |
          echo "BASE_IMAGE_VERSION=$(yq e '.base_image_version' config.yaml)" >> $GITHUB_ENV
          echo "NVM_VERSION=$(yq e '.nvm_version' config.yaml)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(yq e '.node_version' config.yaml)" >> $GITHUB_ENV
          echo "MONGODB_VERSION=$(yq e '.mongodb_version' config.yaml)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(yq e '.tag_version' config.yaml)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . --build-arg BUILD_FROM=$BASE_IMAGE_VERSION --build-arg NVM_VERSION=$NVM_VERSION --build-arg NODE_VERSION=$NODE_VERSION --build-arg MONGODB_VERSION=$MONGODB_VERSION -t my-image-name:$IMAGE_TAG

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/addon-base-ubuntu-node-mongo:${IMAGE_TAG}

      - name: Clean up post build/test
        run: docker rmi my-image-name:$IMAGE_TAG

      - name: Complete
        run: echo "Build and push completed on $(date)"
