name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'config.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["linux/arm64", "linux/amd64"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install yq command-line tool
        run: sudo snap install yq

      - name: Read configuration values from YAML
        run: |
          echo "BUILD_FROM=$(yq e '.build_from' config.yaml)" >> $GITHUB_ENV
          echo "NVM_VERSION=$(yq e '.nvm_version' config.yaml)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(yq e '.node_version' config.yaml)" >> $GITHUB_ENV
          echo "MONGODB_VERSION=$(yq e '.mongodb_version' config.yaml)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(yq e '.tag_version' config.yaml)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase username
        id: lowercase
        run: echo "REPOSITORY_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch }}
          build-args: |
            BUILD_FROM=${{ env.BUILD_FROM }}
            NODE_VERSION=${{ env.NODE_VERSION }}
            MONGODB_VERSION=${{ env.MONGODB_VERSION }}
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWER }}/addon-base-ubuntu-node-mongo:${{ env.IMAGE_TAG }}
          push: true

      - name: Complete
        run: echo "Build and push completed on $(date)"
